[tool.pyright]
include = ["./"]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "./", pythonVersion = "3.11", extraPaths = [ "./" ] }
]
