[tool.pyright]
include = ["./service/"]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "./service/", pythonVersion = "3.11", extraPaths = [ "./service/" ] }
]
